# Generated by Django 4.1.2 on 2022-10-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_name_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
